### ISSUE TITLE
Takes over two hours to install requirements with miniconda

### ISSUE THREAD

**Issue by chriscrsmith** [kr-colab/disperseNN#9]
Need to find good alternative, update README

update: 3 hours

**Comment by silastittes** [comment]
A few thoughts. I basically never use conda anymore because mamba is so much faster. It almost always works as a straight replacement, but see discussion [here](https://github.com/tskit-dev/msprime/issues/2050). 
The easiest way I've found around any mamba issues is to move to the problematic dependencies to the pip section of the yaml (as we now have done for msprime and tskit). 

I think the other option is to move to a proper package with requirements.txt or similar, but that's probably not worth doing for now.

**Comment by andrewkern** [comment]
wait, really?? @chriscrsmith what python / conda version?

**Comment by chriscrsmith** [comment]
That was going to my first question actually. I nuked my conda and I'm trying to simulate a first time user install. What python version version did you use @andrewkern when setting up the conda_env.yml? I'll try adding the python flag with that version to my conda command

**Comment by andrewkern** [comment]
if you just create an env from that file it should default to 3.10 I believe?

**Comment by chriscrsmith** [comment]
and conda 4.12.0, stalled via miniconda

**Comment by andrewkern** [comment]
and this from defaults is taking hours? sheesh

**Comment by chriscrsmith** [comment]
Thanks Silas and Andy mamba worked fine!
